// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/weather_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	weather "github.com/valpere/shopogoda/pkg/weather"
)

// MockWeatherClientInterface is a mock of WeatherClientInterface interface.
type MockWeatherClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherClientInterfaceMockRecorder
}

// MockWeatherClientInterfaceMockRecorder is the mock recorder for MockWeatherClientInterface.
type MockWeatherClientInterfaceMockRecorder struct {
	mock *MockWeatherClientInterface
}

// NewMockWeatherClientInterface creates a new mock instance.
func NewMockWeatherClientInterface(ctrl *gomock.Controller) *MockWeatherClientInterface {
	mock := &MockWeatherClientInterface{ctrl: ctrl}
	mock.recorder = &MockWeatherClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherClientInterface) EXPECT() *MockWeatherClientInterfaceMockRecorder {
	return m.recorder
}

// GeocodeLocation mocks base method.
func (m *MockWeatherClientInterface) GeocodeLocation(ctx context.Context, location string) ([]weather.GeocodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeocodeLocation", ctx, location)
	ret0, _ := ret[0].([]weather.GeocodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeocodeLocation indicates an expected call of GeocodeLocation.
func (mr *MockWeatherClientInterfaceMockRecorder) GeocodeLocation(ctx, location interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeocodeLocation", reflect.TypeOf((*MockWeatherClientInterface)(nil).GeocodeLocation), ctx, location)
}

// GetAirQuality mocks base method.
func (m *MockWeatherClientInterface) GetAirQuality(ctx context.Context, lat, lon float64) (*weather.AirQualityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAirQuality", ctx, lat, lon)
	ret0, _ := ret[0].(*weather.AirQualityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAirQuality indicates an expected call of GetAirQuality.
func (mr *MockWeatherClientInterfaceMockRecorder) GetAirQuality(ctx, lat, lon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAirQuality", reflect.TypeOf((*MockWeatherClientInterface)(nil).GetAirQuality), ctx, lat, lon)
}

// GetCurrentWeather mocks base method.
func (m *MockWeatherClientInterface) GetCurrentWeather(ctx context.Context, lat, lon float64) (*weather.CurrentWeatherResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentWeather", ctx, lat, lon)
	ret0, _ := ret[0].(*weather.CurrentWeatherResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentWeather indicates an expected call of GetCurrentWeather.
func (mr *MockWeatherClientInterfaceMockRecorder) GetCurrentWeather(ctx, lat, lon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentWeather", reflect.TypeOf((*MockWeatherClientInterface)(nil).GetCurrentWeather), ctx, lat, lon)
}

// GetForecast mocks base method.
func (m *MockWeatherClientInterface) GetForecast(ctx context.Context, lat, lon float64) (*weather.ForecastResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForecast", ctx, lat, lon)
	ret0, _ := ret[0].(*weather.ForecastResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForecast indicates an expected call of GetForecast.
func (mr *MockWeatherClientInterfaceMockRecorder) GetForecast(ctx, lat, lon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForecast", reflect.TypeOf((*MockWeatherClientInterface)(nil).GetForecast), ctx, lat, lon)
}

// MockHTTPClientInterface is a mock of HTTPClientInterface interface.
type MockHTTPClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientInterfaceMockRecorder
}

// MockHTTPClientInterfaceMockRecorder is the mock recorder for MockHTTPClientInterface.
type MockHTTPClientInterfaceMockRecorder struct {
	mock *MockHTTPClientInterface
}

// NewMockHTTPClientInterface creates a new mock instance.
func NewMockHTTPClientInterface(ctrl *gomock.Controller) *MockHTTPClientInterface {
	mock := &MockHTTPClientInterface{ctrl: ctrl}
	mock.recorder = &MockHTTPClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClientInterface) EXPECT() *MockHTTPClientInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHTTPClientInterface) Get(url string) (*weather.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", url)
	ret0, _ := ret[0].(*weather.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHTTPClientInterfaceMockRecorder) Get(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHTTPClientInterface)(nil).Get), url)
}
