name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.21
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Test & Quality
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Generate mocks
      run: |
        go install github.com/golang/mock/mockgen@latest
        go generate ./...

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m

    - name: Check code complexity
      run: |
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        echo "Checking cyclomatic complexity (max 15)..."
        gocyclo -over 15 . || echo "::warning::Functions with high complexity found"

    - name: Check code duplication
      run: |
        go install github.com/mibk/dupl@latest
        echo "Checking for code duplication..."
        dupl -threshold 100 ./... || echo "::warning::Code duplication detected"

    - name: Run security scan
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec -fmt sarif -out gosec.sarif ./...

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      with:
        sarif_file: gosec.sarif

    - name: Run unit tests
      env:
        WB_DATABASE_HOST: localhost
        WB_DATABASE_PORT: 5432
        WB_DATABASE_USER: testuser
        WB_DATABASE_PASSWORD: testpass
        WB_DATABASE_NAME: testdb
        WB_DATABASE_SSLMODE: disable
        WB_REDIS_ADDR: localhost:6379
        WB_REDIS_PASSWORD: ""
        WB_BOT_TOKEN: "test_token"
        WB_WEATHER_API_KEY: "test_api_key"
      run: |
        go test -v -race -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html

    - name: Check test coverage
      run: |
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Test coverage: ${COVERAGE}%"
        echo "coverage=${COVERAGE}" >> $GITHUB_OUTPUT

        # Set coverage thresholds based on branch
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          THRESHOLD=25.0
          echo "::notice::Using main branch coverage threshold: ${THRESHOLD}%"
        else
          THRESHOLD=20.0
          echo "::notice::Using development coverage threshold: ${THRESHOLD}%"
        fi

        if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
          echo "::error::Test coverage ${COVERAGE}% is below required ${THRESHOLD}%"
          exit 1
        fi

        # Warn if coverage is below aspirational target (60%)
        if (( $(echo "$COVERAGE < 60.0" | bc -l) )); then
          echo "::warning::Test coverage ${COVERAGE}% is below aspirational target of 60%"
        fi
      id: coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

    # Integration tests disabled temporarily - need refactoring to match current codebase
    # - name: Run integration tests
    #   env:
    #     WB_DATABASE_HOST: localhost
    #     WB_DATABASE_PORT: 5432
    #     WB_DATABASE_USER: testuser
    #     WB_DATABASE_PASSWORD: testpass
    #     WB_DATABASE_NAME: testdb
    #     WB_DATABASE_SSLMODE: disable
    #     WB_REDIS_ADDR: localhost:6379
    #     WB_REDIS_PASSWORD: ""
    #     WB_BOT_TOKEN: "test_token"
    #     WB_WEATHER_API_KEY: "test_api_key"
    #   run: go test -v -tags=integration ./tests/integration/...

    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          coverage.out
          coverage.html
          gosec.sarif

  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/develop'
    environment: staging

    steps:
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment"
        # Add deployment script here
        # Example: kubectl apply -f k8s/staging/

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production environment"
        # Add deployment script here
        # Example: kubectl apply -f k8s/production/

  dependency-check:
    name: Dependency Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run Govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...

  performance-test:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run benchmark tests
      env:
        WB_DATABASE_HOST: localhost
        WB_DATABASE_PORT: 5432
        WB_DATABASE_USER: testuser
        WB_DATABASE_PASSWORD: testpass
        WB_DATABASE_NAME: testdb
        WB_DATABASE_SSLMODE: disable
        WB_REDIS_ADDR: localhost:6379
        WB_REDIS_PASSWORD: ""
        WB_BOT_TOKEN: "test_token"
        WB_WEATHER_API_KEY: "test_api_key"
      run: |
        go test -bench=. -benchmem -benchtime=3s -run=^$ ./... | tee benchmark.txt

    - name: Download previous benchmark results
      uses: actions/cache@v3
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-benchmark-

    - name: Compare benchmark results
      run: |
        if [ -f ./cache/benchmark.txt ]; then
          echo "Comparing with previous benchmark results..."
          go install golang.org/x/perf/cmd/benchstat@latest
          benchstat ./cache/benchmark.txt benchmark.txt > comparison.txt || true
          cat comparison.txt

          # Check for significant performance regressions (>10% slower)
          if grep -q "~" comparison.txt; then
            echo "::warning::Performance changes detected. Review comparison.txt for details."
          fi
        else
          echo "No previous benchmark results found. This will be the baseline."
        fi

        # Save current results for next run
        mkdir -p ./cache
        cp benchmark.txt ./cache/benchmark.txt

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          benchmark.txt
          comparison.txt
