name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: 1.21
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      env:
        CGO_ENABLED: 0
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o shopogoda-linux-amd64 ./cmd/bot
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o shopogoda-linux-arm64 ./cmd/bot
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o shopogoda-darwin-amd64 ./cmd/bot
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o shopogoda-darwin-arm64 ./cmd/bot
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o shopogoda-windows-amd64.exe ./cmd/bot

    - name: Create checksums
      run: |
        sha256sum shopogoda-* > checksums.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        build-args: |
          VERSION=${{ github.ref_name }}

    - name: Generate release notes
      run: |
        # Generate changelog since last tag
        if git describe --tags --abbrev=0 HEAD~1 2>/dev/null; then
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1)
          echo "## Changes since $PREV_TAG" > release-notes.md
          git log --pretty=format:"- %s" $PREV_TAG..HEAD >> release-notes.md
        else
          echo "## First release" > release-notes.md
          echo "Initial release of ShoPogoda weather bot." >> release-notes.md
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release-notes.md
        files: |
          shopogoda-*
          checksums.txt
        generate_release_notes: true
        make_latest: true